-- Create the projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  image_url text not null,
  year text not null,
  description text not null,
  technologies text[] not null, -- Array of strings
  challenge text,
  solution text,
  display_order integer default 0
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- Create a policy that allows anyone to read projects
create policy "Public projects are viewable by everyone"
  on public.projects for select
  using ( true );

-- Create a policy that allows authenticated users to insert/update/delete
-- (For simple email/password auth provided by Supabase)
create policy "Authenticated users can manage projects"
  on public.projects for all
  using ( auth.role() = 'authenticated' );
